-- 1. Create the blog_posts table
CREATE TABLE IF NOT EXISTS public.blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    title TEXT NOT NULL,
    excerpt TEXT NOT NULL,
    content TEXT NOT NULL,
    date TEXT NOT NULL,
    read_time TEXT NOT NULL,
    category TEXT NOT NULL,
    tags TEXT[] DEFAULT '{}'::TEXT[] NOT NULL,
    image_url TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS blog_posts_title_unique
ON public.blog_posts (title);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow public read access (SELECT)
DROP POLICY IF EXISTS "Allow public read access to blog_posts" ON public.blog_posts;
CREATE POLICY "Allow public read access to blog_posts" 
ON public.blog_posts 
FOR SELECT 
USING (true);

-- 4. Restrict blog post writes to one authenticated admin email
DROP POLICY IF EXISTS "Allow admin insert to blog_posts" ON public.blog_posts;
CREATE POLICY "Allow admin insert to blog_posts"
ON public.blog_posts
FOR INSERT
TO authenticated
WITH CHECK ((auth.jwt() ->> 'email') = 'anya.shalaginova@gmail.com');

DROP POLICY IF EXISTS "Allow admin update to blog_posts" ON public.blog_posts;
CREATE POLICY "Allow admin update to blog_posts"
ON public.blog_posts
FOR UPDATE
TO authenticated
USING ((auth.jwt() ->> 'email') = 'anya.shalaginova@gmail.com')
WITH CHECK ((auth.jwt() ->> 'email') = 'anya.shalaginova@gmail.com');

DROP POLICY IF EXISTS "Allow admin delete from blog_posts" ON public.blog_posts;
CREATE POLICY "Allow admin delete from blog_posts"
ON public.blog_posts
FOR DELETE
TO authenticated
USING ((auth.jwt() ->> 'email') = 'anya.shalaginova@gmail.com');

-- 5. Remove starter blog posts
DELETE FROM public.blog_posts
WHERE title IN (
    'The Synergy of Product Management and Business Intelligence',
    'Unlocking Personalization: Building Sitecore-based ML Recommendation Engines',
    'Scaling Agile in Enterprise Systems: A Playbook for M&A Integrations'
);
